# Site settings
title: slaktare.github.io
#email: your-email@domain.com
#description: ""
#baseurl: ""
#url: "http://slaktare.github.io"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
