# Site settings
title: slaktare.github.io
#email: your-email@domain.com
description: "slaktare :-E"
baseurl: ""
url: "http://yourdomain.com"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
